'use client';

import { useState } from 'react';
import {
  Globe,
  Sparkles,
  Rocket,
  Monitor,
  CalendarCheck,
  Megaphone,
  Building2,
  FlaskConical,
  Menu,
  X,
  Check,
  Minus,
  ChevronRight,
} from 'lucide-react';
import { DomainSearch } from './domain-search';

/* ------------------------------------------------------------------ */
/*  Data                                                               */
/* ------------------------------------------------------------------ */

const NAV_LINKS = [
  { label: 'Features', href: '#features' },
  { label: 'Pricing', href: '#pricing' },
  { label: 'For Labs', href: '#features' },
  { label: 'For Clinics', href: '#features' },
];

const STEPS = [
  {
    icon: Globe,
    title: 'Search Your Domain',
    desc: 'Find the perfect .com or .in for your clinic',
  },
  {
    icon: Sparkles,
    title: 'AI Builds Your Website',
    desc: 'Our AI creates a stunning website from your profile in 60 seconds',
  },
  {
    icon: Rocket,
    title: 'Go Live & Grow',
    desc: 'Appointments, billing, marketing — everything works from day one',
  },
];

const FEATURES = [
  {
    icon: Sparkles,
    title: 'AI Website Builder',
    desc: 'Professional website generated by AI. Choose themes, customize content, publish instantly.',
  },
  {
    icon: Globe,
    title: 'Custom Domain',
    desc: 'Your own .com or .in domain. Patients find you at your professional web address.',
  },
  {
    icon: CalendarCheck,
    title: 'Appointments & Billing',
    desc: 'Online booking, queue management, auto-billing, WhatsApp confirmations.',
  },
  {
    icon: Megaphone,
    title: 'Google Business + Marketing',
    desc: 'One-click GBP setup, AI social posts, review collection, SEO optimization.',
  },
  {
    icon: Building2,
    title: 'Hospital Software (HMS)',
    desc: 'Full EMR, OPD queue, nurse triage, pharmacy, LIS — enterprise-grade clinic software.',
  },
  {
    icon: FlaskConical,
    title: 'Hemato Marketplace',
    desc: "Join India's diagnostic marketplace. Lab tests, home collection, phlebotomist network.",
  },
];

const COMPARISON_FEATURES: {
  label: string;
  medihost: string;
  practo: string;
  godaddy: string;
  manual: string;
}[] = [
  { label: 'Custom Domain', medihost: '₹699/yr', practo: '—', godaddy: '₹5000+', manual: '₹1000+' },
  { label: 'AI Website', medihost: '60 seconds', practo: '—', godaddy: 'Hours', manual: 'Days' },
  { label: 'HMS / EMR', medihost: 'Built-in', practo: '—', godaddy: '—', manual: '—' },
  { label: 'Appointments', medihost: 'Built-in', practo: '₹5000/mo', godaddy: '—', manual: '—' },
  { label: 'Google Business', medihost: 'One-click', practo: '—', godaddy: '—', manual: 'Manual' },
  { label: 'Lab Integration', medihost: 'Hemato', practo: '—', godaddy: '—', manual: '—' },
  { label: 'Price', medihost: 'Free to start', practo: '₹5000/mo', godaddy: '₹5000+/yr', manual: '₹50,000+' },
];

const PLANS = [
  {
    name: 'Starter',
    price: 'Free',
    period: 'forever',
    badge: null,
    features: ['Subdomain (yourname.medihost.in)', 'Basic AI website', '1 doctor profile', '50 appointments/month', 'Basic analytics'],
    cta: 'Get Started Free',
    highlight: false,
  },
  {
    name: 'Professional',
    price: '₹999',
    period: '/month',
    badge: null,
    features: ['Custom .com / .in domain', 'Full AI website + themes', 'Up to 5 doctors', '500 appointments/month', 'EMR + billing', 'Google Business setup', 'WhatsApp notifications'],
    cta: 'Start 14-Day Trial',
    highlight: false,
  },
  {
    name: 'Business',
    price: '₹2,999',
    period: '/month',
    badge: 'Most Popular',
    features: ['Everything in Professional', 'LIS + pharmacy module', 'AI marketing suite', 'Unlimited doctors', 'Unlimited appointments', 'Priority support', 'Custom integrations', 'Hemato marketplace listing'],
    cta: 'Start 14-Day Trial',
    highlight: true,
  },
];

const TRUST_STATS = [
  { value: '500+', label: 'Clinics' },
  { value: '50+', label: 'Labs' },
  { value: '10,000+', label: 'Patients' },
  { value: 'Hyderabad', label: '& Growing' },
];

const FOOTER_COLS = [
  {
    title: 'Product',
    links: ['AI Website Builder', 'Custom Domains', 'Appointments', 'Billing & EMR', 'Marketing Suite', 'Hemato Marketplace'],
  },
  {
    title: 'Resources',
    links: ['Documentation', 'Blog', 'Help Center', 'API Reference', 'Status Page'],
  },
  {
    title: 'Company',
    links: ['About Us', 'Careers', 'Contact', 'Partners', 'Press'],
  },
  {
    title: 'Legal',
    links: ['Privacy Policy', 'Terms of Service', 'Cookie Policy', 'HIPAA Compliance', 'Refund Policy'],
  },
];

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function LandingPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <div className="min-h-screen bg-white text-gray-900 scroll-smooth">
      {/* ===== Sticky Nav ===== */}
      <nav className="fixed top-0 inset-x-0 z-50 bg-white/90 backdrop-blur-lg border-b border-gray-100">
        <div className="max-w-7xl mx-auto flex items-center justify-between px-4 sm:px-6 h-16">
          {/* Logo */}
          <a href="#" className="flex items-center gap-2 text-xl font-extrabold tracking-tight">
            <span className="text-emerald-600">+</span>
            <span>
              Medi<span className="text-emerald-600">Host</span>
            </span>
          </a>

          {/* Desktop links */}
          <div className="hidden md:flex items-center gap-8">
            {NAV_LINKS.map((l) => (
              <a
                key={l.label}
                href={l.href}
                className="text-sm font-medium text-gray-600 hover:text-emerald-700 transition-colors"
              >
                {l.label}
              </a>
            ))}
          </div>

          {/* Desktop CTAs */}
          <div className="hidden md:flex items-center gap-3">
            <a
              href="/login"
              className="px-4 py-2 text-sm font-medium text-gray-700 border border-gray-300 rounded-xl hover:border-emerald-500 hover:text-emerald-700 transition-colors"
            >
              Login
            </a>
            <a
              href="#pricing"
              className="px-5 py-2 text-sm font-semibold text-white bg-emerald-600 rounded-xl hover:bg-emerald-700 transition-colors"
            >
              Get Started Free
            </a>
          </div>

          {/* Mobile hamburger */}
          <button
            className="md:hidden p-2 text-gray-700"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Toggle menu"
          >
            {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>

        {/* Mobile menu */}
        {mobileMenuOpen && (
          <div className="md:hidden bg-white border-t border-gray-100 px-4 pb-4">
            {NAV_LINKS.map((l) => (
              <a
                key={l.label}
                href={l.href}
                onClick={() => setMobileMenuOpen(false)}
                className="block py-3 text-sm font-medium text-gray-700 hover:text-emerald-700 border-b border-gray-50"
              >
                {l.label}
              </a>
            ))}
            <div className="flex flex-col gap-2 mt-3">
              <a
                href="/login"
                className="px-4 py-2.5 text-sm font-medium text-center text-gray-700 border border-gray-300 rounded-xl"
              >
                Login
              </a>
              <a
                href="#pricing"
                className="px-4 py-2.5 text-sm font-semibold text-center text-white bg-emerald-600 rounded-xl"
              >
                Get Started Free
              </a>
            </div>
          </div>
        )}
      </nav>

      {/* ===== Hero Section ===== */}
      <section className="pt-28 pb-16 sm:pt-36 sm:pb-24 bg-gradient-to-b from-gray-50 to-white">
        <div className="max-w-4xl mx-auto px-4 text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-1.5 mb-6 bg-emerald-50 text-emerald-700 rounded-full text-sm font-medium border border-emerald-200">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            Now live in Hyderabad
          </div>

          {/* Headline */}
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight leading-tight">
            Your Clinic&apos;s{' '}
            <span className="text-emerald-600">Digital Identity</span>
            <br className="hidden sm:block" />
            {' '}— Built in 60 Seconds
          </h1>

          {/* Subtext */}
          <p className="mt-6 text-lg sm:text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
            AI-powered website, custom domain, appointments, billing, EMR, and marketing — all in one
            platform. No tech skills needed.
          </p>

          {/* Domain Search */}
          <div className="mt-10">
            <DomainSearch />
          </div>
        </div>
      </section>

      {/* ===== How It Works ===== */}
      <section className="py-20 sm:py-28 bg-white" id="how-it-works">
        <div className="max-w-5xl mx-auto px-4">
          <h2 className="text-center text-3xl sm:text-4xl font-extrabold tracking-tight">
            How It Works
          </h2>
          <p className="text-center text-gray-500 mt-3 text-lg">Three steps to your clinic&apos;s digital presence</p>

          <div className="mt-14 grid grid-cols-1 md:grid-cols-3 gap-10">
            {STEPS.map((s, i) => (
              <div key={s.title} className="text-center">
                <div className="mx-auto w-16 h-16 flex items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600 mb-5">
                  <s.icon className="w-7 h-7" />
                </div>
                <div className="text-xs font-bold text-emerald-600 uppercase tracking-wider mb-2">
                  Step {i + 1}
                </div>
                <h3 className="text-xl font-bold mb-2">{s.title}</h3>
                <p className="text-gray-500 leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== Features Grid ===== */}
      <section className="py-20 sm:py-28 bg-gray-50" id="features">
        <div className="max-w-6xl mx-auto px-4">
          <h2 className="text-center text-3xl sm:text-4xl font-extrabold tracking-tight">
            Everything Your Clinic Needs
          </h2>
          <p className="text-center text-gray-500 mt-3 text-lg">
            One platform, zero headaches
          </p>

          <div className="mt-14 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="bg-white rounded-2xl p-7 border border-gray-200 hover:border-emerald-300 hover:shadow-lg transition-all"
              >
                <div className="w-12 h-12 flex items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 mb-4">
                  <f.icon className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-bold mb-2">{f.title}</h3>
                <p className="text-gray-500 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== Comparison Table ===== */}
      <section className="py-20 sm:py-28 bg-white" id="comparison">
        <div className="max-w-5xl mx-auto px-4">
          <h2 className="text-center text-3xl sm:text-4xl font-extrabold tracking-tight">
            Why MediHost vs Others
          </h2>
          <p className="text-center text-gray-500 mt-3 text-lg">
            See how we compare — honestly
          </p>

          <div className="mt-12 overflow-x-auto rounded-2xl border border-gray-200">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 text-left">
                  <th className="px-5 py-4 font-semibold text-gray-700">Feature</th>
                  <th className="px-5 py-4 font-semibold text-emerald-700">MediHost</th>
                  <th className="px-5 py-4 font-semibold text-gray-700">Practo</th>
                  <th className="px-5 py-4 font-semibold text-gray-700">GoDaddy+Wix</th>
                  <th className="px-5 py-4 font-semibold text-gray-700">Manual</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {COMPARISON_FEATURES.map((row) => (
                  <tr key={row.label} className="hover:bg-gray-50 transition-colors">
                    <td className="px-5 py-3.5 font-medium text-gray-800">{row.label}</td>
                    <td className="px-5 py-3.5">
                      <span className="inline-flex items-center gap-1.5 text-emerald-700 font-medium">
                        <Check className="w-4 h-4" />
                        {row.medihost}
                      </span>
                    </td>
                    <td className="px-5 py-3.5 text-gray-500">
                      {row.practo === '—' ? (
                        <Minus className="w-4 h-4 text-gray-300" />
                      ) : (
                        row.practo
                      )}
                    </td>
                    <td className="px-5 py-3.5 text-gray-500">
                      {row.godaddy === '—' ? (
                        <Minus className="w-4 h-4 text-gray-300" />
                      ) : (
                        row.godaddy
                      )}
                    </td>
                    <td className="px-5 py-3.5 text-gray-500">
                      {row.manual === '—' ? (
                        <Minus className="w-4 h-4 text-gray-300" />
                      ) : (
                        row.manual
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* ===== Pricing ===== */}
      <section className="py-20 sm:py-28 bg-gray-50" id="pricing">
        <div className="max-w-6xl mx-auto px-4">
          <h2 className="text-center text-3xl sm:text-4xl font-extrabold tracking-tight">
            Simple, Transparent Pricing
          </h2>
          <p className="text-center text-gray-500 mt-3 text-lg">
            Start free, upgrade when you&apos;re ready
          </p>

          <div className="mt-14 grid grid-cols-1 md:grid-cols-3 gap-6 items-start">
            {PLANS.map((plan) => (
              <div
                key={plan.name}
                className={`relative rounded-2xl p-7 border-2 transition-all ${
                  plan.highlight
                    ? 'border-emerald-500 bg-white shadow-xl scale-[1.02]'
                    : 'border-gray-200 bg-white hover:border-emerald-300 hover:shadow-md'
                }`}
              >
                {plan.badge && (
                  <div className="absolute -top-3.5 left-1/2 -translate-x-1/2 px-4 py-1 bg-emerald-600 text-white text-xs font-bold rounded-full">
                    {plan.badge}
                  </div>
                )}
                <h3 className="text-lg font-bold">{plan.name}</h3>
                <div className="mt-3 flex items-baseline gap-1">
                  <span className="text-4xl font-extrabold">{plan.price}</span>
                  <span className="text-gray-500 text-sm">{plan.period}</span>
                </div>
                <ul className="mt-6 space-y-3">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-start gap-2 text-sm text-gray-600">
                      <Check className="w-4 h-4 text-emerald-500 mt-0.5 shrink-0" />
                      {f}
                    </li>
                  ))}
                </ul>
                <button
                  className={`mt-8 w-full py-3 rounded-xl font-semibold text-sm transition-colors ${
                    plan.highlight
                      ? 'bg-emerald-600 text-white hover:bg-emerald-700'
                      : 'bg-gray-100 text-gray-800 hover:bg-emerald-50 hover:text-emerald-700'
                  }`}
                >
                  {plan.cta}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== Trust Section ===== */}
      <section className="py-20 sm:py-28 bg-white">
        <div className="max-w-5xl mx-auto px-4 text-center">
          {/* Badges */}
          <div className="flex flex-wrap items-center justify-center gap-4 mb-14">
            {['HIPAA', 'NABL', 'ABDM', 'GST', 'ISO 27001'].map((badge) => (
              <span
                key={badge}
                className="px-5 py-2 bg-gray-100 text-gray-700 text-sm font-semibold rounded-lg border border-gray-200"
              >
                {badge}
              </span>
            ))}
          </div>

          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {TRUST_STATS.map((s) => (
              <div key={s.label}>
                <div className="text-3xl sm:text-4xl font-extrabold text-emerald-600">
                  {s.value}
                </div>
                <div className="mt-1 text-gray-500 text-sm font-medium">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== CTA Section ===== */}
      <section className="py-20 sm:py-28 bg-emerald-600">
        <div className="max-w-3xl mx-auto px-4 text-center">
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Ready to take your clinic online?
          </h2>
          <p className="mt-4 text-emerald-100 text-lg">
            Get started in 60 seconds — no credit card required
          </p>
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
            <a
              href="#pricing"
              className="inline-flex items-center gap-2 px-8 py-4 bg-white text-emerald-700 font-bold rounded-xl text-lg hover:bg-emerald-50 transition-colors shadow-lg"
            >
              Get Started Free
              <ChevronRight className="w-5 h-5" />
            </a>
            <a
              href="#"
              className="text-emerald-100 underline underline-offset-4 hover:text-white transition-colors font-medium"
            >
              Or contact sales
            </a>
          </div>
        </div>
      </section>

      {/* ===== Footer ===== */}
      <footer className="bg-gray-900 text-gray-400 pt-16 pb-8">
        <div className="max-w-6xl mx-auto px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-12">
            {FOOTER_COLS.map((col) => (
              <div key={col.title}>
                <h4 className="text-white font-semibold text-sm mb-4">{col.title}</h4>
                <ul className="space-y-2.5">
                  {col.links.map((link) => (
                    <li key={link}>
                      <a
                        href="#"
                        className="text-sm hover:text-emerald-400 transition-colors"
                      >
                        {link}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="border-t border-gray-800 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
            <p className="text-sm text-center sm:text-left">
              &copy; 2026 SmartGumastha Technologies. MediHost&trade; — We Deliver Health.
            </p>
            <div className="flex items-center gap-4 text-sm">
              <a href="#" className="hover:text-emerald-400 transition-colors">Twitter</a>
              <a href="#" className="hover:text-emerald-400 transition-colors">LinkedIn</a>
              <a href="#" className="hover:text-emerald-400 transition-colors">Instagram</a>
              <a href="#" className="hover:text-emerald-400 transition-colors">YouTube</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
